# Generated by Django 5.1.3 on 2025-12-05 09:03

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UniversitySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=1, verbose_name='Порядковый номер')),
                ('title', models.CharField(max_length=255, verbose_name='Название раздела')),
                ('short_description', models.TextField(verbose_name='Краткое описание')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Полное описание')),
            ],
            options={
                'verbose_name': 'Раздел университета',
                'verbose_name_plural': 'Разделы университета',
                'ordering': ['number'],
            },
        ),
    ]
