# Generated by Django 5.1.3 on 2025-12-05 09:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название университета')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание университета')),
                ('sections', models.ManyToManyField(related_name='universities', to='university.universitysection', verbose_name='Разделы университета')),
            ],
            options={
                'verbose_name': 'Университет',
                'verbose_name_plural': 'Университеты',
            },
        ),
    ]
