# Generated by Django 5.1.3 on 2025-12-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_university'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='universities/gallery/', verbose_name='Фото')),
                ('caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подпись к фото')),
            ],
        ),
        migrations.AddField(
            model_name='university',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='universities/main/', verbose_name='Главное фото'),
        ),
        migrations.AddField(
            model_name='university',
            name='gallery_images',
            field=models.ManyToManyField(blank=True, related_name='universities', to='university.universityimage', verbose_name='Дополнительные фото'),
        ),
    ]
