# Generated by Django 5.1.3 on 2025-12-05 10:30

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_universityimage_university_main_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='universityimage',
            options={'verbose_name': 'Фото университета', 'verbose_name_plural': 'Фото университета'},
        ),
        migrations.AlterField(
            model_name='university',
            name='gallery_images',
            field=models.ManyToManyField(blank=True, related_name='universities', to='university.universityimage', verbose_name='Галерея изображений'),
        ),
        migrations.AlterField(
            model_name='university',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='university_images/'),
        ),
        migrations.AlterField(
            model_name='university',
            name='sections',
            field=models.ManyToManyField(blank=True, related_name='universities', to='university.universitysection', verbose_name='Разделы университета'),
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название программы')),
                ('faculty', models.CharField(max_length=255, verbose_name='Факультет')),
                ('passing_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Проходной балл')),
                ('code', models.CharField(max_length=20, verbose_name='Код программы')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание программы')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='university.university', verbose_name='Университет')),
            ],
            options={
                'verbose_name': 'Программа обучения',
                'verbose_name_plural': 'Программы обучения',
            },
        ),
    ]
