# Generated by Django 5.1.3 on 2025-12-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_alter_universityimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на программу'),
        ),
    ]
