# Generated by Django 5.1.3 on 2025-12-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_program_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='programs_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на программы университета'),
        ),
    ]
