# Generated by Django 5.1.3 on 2025-12-05 12:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0006_university_programs_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='admission',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Информация о поступлении'),
        ),
    ]
