# Generated by Django 5.1.3 on 2025-12-05 12:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0007_university_admission'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='international_cooperation',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Международное сотрудничество'),
        ),
    ]
