# Generated by Django 5.1.3 on 2025-12-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0008_university_international_cooperation'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='QS_Asia_University_Rankings',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Место в рейтинге QS Asia'),
        ),
        migrations.AddField(
            model_name='university',
            name='World_University_Rankings_2024',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Место в мировом рейтинге университетов 2024'),
        ),
    ]
