# Generated by Django 5.1.3 on 2025-12-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0009_university_qs_asia_university_rankings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='d_tour',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на 3D-тур по университету'),
        ),
    ]
