# Generated by Django 5.1.3 on 2025-12-05 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0010_university_d_tour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='World_University_Rankings_2024',
            new_name='World_University_Rankings',
        ),
    ]
