# Generated by Django 5.1.3 on 2025-12-05 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0011_rename_world_university_rankings_2024_university_world_university_rankings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='QS_Asia_University_Rankings',
        ),
        migrations.RemoveField(
            model_name='university',
            name='World_University_Rankings',
        ),
        migrations.CreateModel(
            name='UniversityRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(max_length=100, verbose_name='Система рейтинга (QS, QS Asia, THE, ARWU...)')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год рейтинга')),
                ('rank_from', models.PositiveIntegerField(blank=True, null=True, verbose_name='Рейтинг от')),
                ('rank_to', models.PositiveIntegerField(blank=True, null=True, verbose_name='Рейтинг до')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='university.university')),
            ],
            options={
                'verbose_name': 'Рейтинг университета',
                'verbose_name_plural': 'Рейтинги университета',
            },
        ),
    ]
