# Generated by Django 5.1.3 on 2025-12-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0013_university_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='faculties',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество факультетов'),
        ),
        migrations.AddField(
            model_name='university',
            name='specializations',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество специальностей'),
        ),
    ]
