# Generated by Django 5.1.3 on 2025-12-06 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0014_university_faculties_university_specializations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='faculties',
        ),
        migrations.AddField(
            model_name='university',
            name='stipends_dollars',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Размер стипендии (в долларах)'),
        ),
        migrations.AlterField(
            model_name='university',
            name='specializations',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество образовательных программ'),
        ),
    ]
