# Generated by Django 5.1.3 on 2025-12-06 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0015_remove_university_faculties_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='stipends_dollars',
        ),
        migrations.AddField(
            model_name='university',
            name='stipends_bk_dollars',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Размер стипендии баклавра (в долларах)'),
        ),
        migrations.AddField(
            model_name='university',
            name='stipends_mg_dollars',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Размер стипендии магистра (в долларах)'),
        ),
        migrations.AddField(
            model_name='university',
            name='tuition_doc_dollars',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Стоимость стипендии доктора (в долларах)'),
        ),
    ]
