# Generated by Django 5.1.3 on 2025-12-06 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0016_remove_university_stipends_dollars_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='stipends_bk_dollars',
        ),
        migrations.RemoveField(
            model_name='university',
            name='stipends_mg_dollars',
        ),
        migrations.RemoveField(
            model_name='university',
            name='tuition_doc_dollars',
        ),
        migrations.AddField(
            model_name='university',
            name='stipends_bk',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Размер стипендии баклавра'),
        ),
        migrations.AddField(
            model_name='university',
            name='stipends_mg',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Размер стипендии магистра'),
        ),
        migrations.AddField(
            model_name='university',
            name='tuition_doc',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Стоимость стипендии доктора'),
        ),
    ]
