# Generated by Django 5.1.3 on 2025-12-06 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0017_remove_university_stipends_bk_dollars_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='tuition_doc',
            new_name='stipends_doc',
        ),
    ]
