# Generated by Django 5.1.3 on 2025-12-06 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_pos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, verbose_name='Ник')),
                ('text', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время отправки')),
            ],
        ),
    ]
