# Generated by Django 5.1.3 on 2025-12-06 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0018_rename_tuition_doc_university_stipends_doc'),
        ('user_pos', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='university',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='university.university'),
            preserve_default=False,
        ),
    ]
